default: true
"ul-indent": { "indent": 4 }
"heading-style": { "style": "atx" }
# False positives in equations
"no-reversed-links": false
"line-length": false
"ol-prefix": { "style": "ordered" }
"no-inline-html":
  allowed_elements:
    - "div"
# Tables give this false positives
"hr-style": false
