rules:
  apostrophe: false,
  common-misspellings: true,
  diacritics: true,
  "no-dead-link": true,
  "stop-words":
    defaultWords: true,
    words:
      - simply
      - obviously
      - basically
      - clearly
      - just
      - easy
      - so
      - "everyone knows"
      - fantastic
    exclude:
      - principal
      - magnitude
      - c
      - s
      - o
      - f
      - resistance
      - "relative to"
  terminology:
    defaultTerms: true
    terms:
      - HOOMD-blue
      - [hoomd, HOOMD-blue]
      - Vogel--Tammann--Fulcher

  alex: false
  "write-good": true,
  "unexpanded-acronym":
    ignore_acronyms:
      - "HOOMD"
      - "UMAP"
  "no-start-duplicated-conjunction":
    interval: 2
  "max-comma":
    max: 3
  "abbr-within-parentheses": true
