name: thesis
dependencies:
  - python==3.6
  - pip
  - wheel
  - setuptools
  - pandoc
  - conda-forge::tectonic==0.1.11
  - malramsay::biber==2.5
  - pre_commit
  - pip:
    - pandoc-eqnos
    - pandoc-fignos
    - pandoc-tablenos
