name: thesis
dependencies:
  - python=3.7
  - conda-forge::pandoc==2.10
  - conda-forge::tectonic==0.3.3
  - malramsay::biber==2.14
  - conda-forge::pre-commit==2.6.0
  - nodejs==10.13.0
  - conda-forge::graphviz==2.42.3
  - conda-forge::cairosvg==2.4.2
  - conda-forge::pandocfilters==1.4.2
  - conda-forge::pandoc-crossref==0.3.7
  - conda-forge::hsluv==0.0.2
  - conda-forge::open-fonts==0.5.1
  - pip=19.3
  - pip:
      - gitlint==0.12.0
