name: thesis
dependencies:
  - python=3.7
  - conda-forge::pandoc==2.9
  - conda-forge::tectonic==0.1.12
  - malramsay::biber==2.11
  - conda-forge::pre-commit==2.6.0
  - nodejs==10.13.0
  - conda-forge::graphviz==2.42.3
  - conda-forge::cairosvg==2.4.2
  - conda-forge::pandocfilters==1.4.2
  - conda-forge::pandoc-crossref==0.3.6.4
  - conda-forge::hsluv==0.0.2
  - conda-forge::open-fonts==0.5.1
  - pip=20.1.1
  - pip:
      - gitlint==0.12.0
