name: thesis
dependencies:
  - python=3.7
  - pip=19.3
  - setuptools==41.0.1
  - pandoc==2.7.3
  - conda-forge::tectonic==0.1.11
  - malramsay::biber==2.11
  - pre_commit=1.18
  - nodejs==10.13.0
  - conda-forge::graphviz==2.42.3
  - conda-forge::cairosvg==2.4.2
  - conda-forge::pandocfilters==1.4.2
  - conda-forge::pandoc-crossref==0.3.4.2
  - pip:
      - hsluv==0.0.2
      - gitlint==0.12.0
