version: 1
update_configs:
  # Keep package.json (& lockfiles) up to date, batching weekly
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
  # Keep submodules up to date, batching weekly
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "weekly"
