name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install environment using conda
      run: $CONDA/bin/conda env create
      
    - name: Ensure style is correct
      run: source $CONDA/bin/activate thesis && make style
    
    - name: Ensure grammar is correct
      run: source $CONDA/bin/activate thesis && make grammar
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          
      - name: Install environment using conda
        run: $CONDA/bin/conda env create
      
      - name: Compile
        run: source $CONDA/bin/activate thesis && make
