name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: actions/setup-node@v1
    - run: npm install

    - name: Ensure style is correct
      run: make style

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: actions/cache@preview
        id: cache
        with:
          path: ~/.cache/Tectonic
          key: tectonic_cache

      - name: Install environment using conda
        run: $CONDA/bin/conda env create

      - name: Compile
        run: source $CONDA/bin/activate thesis && make
