name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install environment using conda
      run: conda env create && source activate thesis
      env:
        PATH: $CONDA/bin:$PATH
      
    - name: Ensure style is correct
      run: make style
      env:
        PATH: $CONDA/bin:$PATH
    
    - name: Ensure grammar is correct
      run: make grammar
      env:
        PATH: $CONDA/bin:$PATH
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          
      - name: Install environment using conda
        run: conda env create && source activate thesis
        env:
          PATH: $CONDA/bin:$PATH
      
      - name: Compile
        run: make
        env:
          PATH: $CONDA/bin:$PATH
