name: Style Linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
    - run: npm install

    - name: Ensure style is correct
      run: make style
